// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function twoFer(msg) {
  if (msg !== undefined) {
    return "One for " + (msg + ", one for me.");
  } else {
    return "One for you, one for me.";
  }
}

exports.twoFer = twoFer;
/* No side effect */
