// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ResistorColor$ResistorColor = require("../src/ResistorColor.bs.js");

Jest.describe("Resistor Color", (function (param) {
        Jest.test("Black", (function (param) {
                return Jest.Expect.toEqual(0, Jest.Expect.expect(ResistorColor$ResistorColor.colorCode(/* Black */0)));
              }));
        Jest.test("White", (function (param) {
                return Jest.Expect.toEqual(9, Jest.Expect.expect(ResistorColor$ResistorColor.colorCode(/* White */9)));
              }));
        return Jest.test("Orange", (function (param) {
                      return Jest.Expect.toEqual(3, Jest.Expect.expect(ResistorColor$ResistorColor.colorCode(/* Orange */3)));
                    }));
      }));

/*  Not a pure module */
