// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function colorCode(color) {
  switch (color) {
    case /* Black */0 :
        return 0;
    case /* Orange */3 :
        return 3;
    case /* Brown */1 :
    case /* Red */2 :
    case /* Yellow */4 :
    case /* Green */5 :
    case /* Blue */6 :
    case /* Violet */7 :
    case /* Grey */8 :
        break;
    case /* White */9 :
        return 9;
    
  }
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "ResistorColor.re",
          13,
          25
        ]
      ];
}

exports.colorCode = colorCode;
/* No side effect */
